ChequeClearingSystem/urls.py
from django.conf.urls import url

from . import views

app_name = 'ChequeClearingSystem'
'''
list of patterns for url for redirection
'''
urlpatterns = [
    url(r'^register', views.UserFormView.as_view(), name='register'),
    url(r'^profile', views.details, name='profile'),
    url(r'^new_account', views.createAccountHolder, name='new_account'),
    url(r'^', views.LoginFormView.as_view(), name='main'),
    url(r'^logout', views.logout_view, name='logout'),

]

ChequeClearingSystemProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^main/', include('ChequeClearingSystem.urls')),

    # url(r'^/',include('ChequeClearingSystem.urls'))
]

ChequeClearingSystem/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now

d = datetime.date(1970, 1, 1)  # default date


class AccountHolder(models.Model):
    '''
    abstract model for Bank Database
    '''
    accountNumber = models.IntegerField(unique=True, default=1000000, verbose_name='Account Number')
    full_name = models.CharField(max_length=100, verbose_name='Name')
    gender = models.CharField(max_length=1, choices={('M', 'Male'), ('F', 'Female')}, verbose_name='Gender')
    fatherName = models.CharField(max_length=100, verbose_name='Father\'s Name')
    motherName = models.CharField(max_length=100, verbose_name='Mother\'s Name')
    email = models.EmailField(unique=True, verbose_name='Email')
    pan = models.CharField(max_length=10, verbose_name='PAN Number')
    contactNumber = models.IntegerField(verbose_name='Contact Number')
    profilePicture = models.FileField(default='images/male_profile.png', verbose_name='Photograph')
    signature = models.FileField(default='images/female.jpg', verbose_name='Signature')
    dateOfBirth = models.DateField(default=d, verbose_name='Date of Birth')
    balance = models.IntegerField(default=10000, verbose_name='Balance')
    lastTransaction = models.DateTimeField(verbose_name='Last Transaction', null=True, blank=True, default=None)

    class Meta:
        abstract = True


class cheque(models.Model):
    '''
    abstract model for Cheque Database
    '''
    cheque = models.FileField(verbose_name='Cheque Image')
    amount = models.IntegerField(verbose_name='Amount')
    chequeNumber = models.IntegerField(verbose_name='Account Number')

    class Meta:
        abstract = True


class payeeBank(AccountHolder):
    '''
    model For payee Bank
    '''

    def __str__(self):
        return self.full_name + '--' + str(self.accountNumber) + '--' + str(self.contactNumber)


class bearerBank(AccountHolder):
    '''
    model for Bearer Bank
    '''
    user = models.OneToOneField(User, default=None, on_delete=models.SET_NULL, null=True, blank=True)
    registered = models.BooleanField(default=False, verbose_name='Account Registered')

    def __str__(self):
        return self.full_name + '--' + str(self.accountNumber) + '--' + str(self.contactNumber)


class payeeBankCheque(cheque):
    '''
    model for Cheques for payee Bank
    '''
    timeDeposited = models.DateTimeField(default=now, verbose_name='Time Deposited')
    payee = models.ForeignKey(payeeBank, default=1, on_delete=models.DO_NOTHING, verbose_name='Payee')
    bearer = models.ForeignKey(bearerBank, default=1, on_delete=models.DO_NOTHING, verbose_name='Bearer')

    def __str__(self):
        return str(self.chequeNumber) + ' ' + str(self.amount) + " " + str(self.timeDeposited)


class bearerBankCheque(cheque):
    '''
    model for Cheques for Bearer Bank
    '''
    timeDeposited = models.DateTimeField(default=now, verbose_name='Time Deposited')
    payee = models.ForeignKey(payeeBank, default=1, on_delete=models.DO_NOTHING, verbose_name='Payee')
    bearer = models.ForeignKey(bearerBank, default=1, on_delete=models.DO_NOTHING, verbose_name='Bearer')

    def __str__(self):
        return str(self.chequeNumber) + ' ' + str(self.amount) + ' ' + str(self.timeDeposited)

ChequeClearingSystem/forms.py
from django import forms
from django.contrib.auth.models import User

from ChequeClearingSystem.models import bearerBankCheque, bearerBank


class UserForm(forms.ModelForm):
    '''
    User Form for registering new user
    '''
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailInput()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        required = ['username', 'email', 'password']


class LoginForm(forms.Form):
    '''
    Login Form
    '''
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    fields = ['username', 'password']


class AccountRegister(forms.Form):
    '''
    Form to register bank account with user
    '''
    name = forms.CharField(widget=forms.TextInput())
    fatherName = forms.CharField(widget=forms.TextInput())
    email = forms.EmailField(widget=forms.EmailInput)
    contactNumber = forms.IntegerField(widget=forms.NumberInput())
    accountNumber = forms.IntegerField(widget=forms.NumberInput())

    class Meta:
        model = bearerBank
        fields = ['accountNumber', 'name', 'fatherName', 'email', 'contactNumber']


class chequeUpload(forms.ModelForm):
    '''
    Form for accepting cheque
    '''
    cheque = forms.FileField(widget=forms.FileInput())
    accountNumber = forms.IntegerField()

    class Meta:
        model = bearerBankCheque
        fields = ['accountNumber', 'amount', 'cheque']

ChequeClearingSystem/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import View

from ChequeClearingSystemProject.settings import BASE_DIR
from confirmationMessages import sendMessage
from processing import processing
from .forms import UserForm, LoginForm, AccountRegister, chequeUpload
from .models import bearerBank, payeeBank, payeeBankCheque


class UserFormView(View):
    '''
    form view to registering new user
    '''
    form_class = UserForm
    template_name = 'ChequeClearingSystem/registration_form.html'

    def get(self, request):
        logout(request)
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # cleaned(normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # authenticate
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    print("login")
                    return redirect('ChequeClearingSystem:profile')

            return render(request, self.template_name, {'form': form})


class LoginFormView(View):
    '''
    form view for Login
    '''
    form_class = LoginForm
    template_name = 'ChequeClearingSystem/login.html'

    def get(self, request):
        logout(request)
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    print("Login")
                    return redirect('ChequeClearingSystem:profile')
        return redirect('ChequeClearingSystem:main')


@login_required(login_url='/main')
def logout_view(request):
    '''
    logout view
    :param request: request object
    :return: redirects to login
    '''
    logout(request)
    print("logout")
    return redirect('ChequeClearingSystem:main')


IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


@login_required(login_url='/main')
def createAccountHolder(request):
    '''
    To register account with user
    :param request: request object
    :return: redirects to login page ,details page,register account page
    '''
    if not request.user.is_authenticated:  # unauthenticated user
        return render(request, 'ChequeClearingSystem/login.html')
    else:
        form = AccountRegister(request.POST or None)
        if form.is_valid():  # check if form is valid
            # extract detais
            accountNumber = form.cleaned_data['accountNumber']
            name = form.cleaned_data['name']
            fatherName = form.cleaned_data['fatherName']
            contactNumber = form.cleaned_data['contactNumber']
            email = form.cleaned_data['email']

            # get details from bearerBank database and check if account exists
            bankAccount = bearerBank.objects.filter(accountNumber=accountNumber)
            accountOfUser = list()
            for accounts in bankAccount:
                accountOfUser.append((accounts.accountNumber, accounts.full_name, accounts.fatherName,
                                      accounts.contactNumber, accounts.email))
            enteredData = (accountNumber, name, fatherName, contactNumber, email)
            bankAccount = bankAccount.values()
            bankAccount = list(bankAccount)
            bankAccount = bankAccount[0]
            temp = bankAccount
            bankAccount = list()
            for x in temp:
                bankAccount.append(temp[x])

            bankAccount = bearerBank(*bankAccount)

            # registers account
            if (enteredData == accountOfUser[0] and bankAccount.registered is False):
                bankAccount.registered = True
                bankAccount.user = request.user
                bankAccount.save(update_fields=['registered', 'user'])
                return redirect('ChequeClearingSystem:profile')

        # for unregistered account
        context = {
            "form": AccountRegister(),
        }
        messages = 'Data Entered is Invalid'
        context['msg'] = messages
        return render(request, 'ChequeClearingSystem/new_account.html', context)


@login_required(login_url='/main')
def details(request):
    '''
    to display user details and accept the cheque
    :param request:
    :return: redirects to appropriate page
    '''
    # get user account details from database
    profile = bearerBank.objects.filter(user=request.user, registered=True)
    details = None
    if profile:
        details = dict()
        profile = profile[0]
        details['accountNumber'] = profile.accountNumber
        details['name'] = profile.full_name
        details['fatherName'] = profile.fatherName
        details['balance'] = profile.balance
        details['profilePicture'] = profile.profilePicture.url
        details['dateOfBirth'] = profile.dateOfBirth
        details['pan'] = profile.pan

    if not request.user.is_authenticated:  # unauthenticated user
        return redirect('ChequeClearingSystem:main')
    elif request.POST:  # post request
        form = chequeUpload(request.POST or None, request.FILES or None)
        if form.is_valid():
            # extract details and files from form
            chequeDetails = form.save(commit=False)
            chequeDetails.accountNumber = form.cleaned_data['accountNumber']
            chequeDetails.amount = form.cleaned_data['amount']
            chequeDetails.cheque = request.FILES['cheque']
            file_type_sign = chequeDetails.cheque.url.split('.')[-1]
            file_type_sign = file_type_sign.lower()
            accountHolder = bearerBank.objects.filter(user=request.user)
            accountNumberUser = list()

            for accounts in accountHolder:
                accountNumberUser.append(accounts.accountNumber)

            # cheque if account exists in database and user is registered with that account
            if chequeDetails.accountNumber not in accountNumberUser:
                context = {
                    'chequeDetails': chequeDetails,
                    'form': chequeUpload(),
                    'msg': 'No account',
                    'details': details
                }
                return render(request, 'ChequeClearingSystem/details.html', context)

            # Create entry in bearer bank database
            accountHolder = bearerBank.objects.filter(accountNumber=chequeDetails.accountNumber)
            accountHolder = accountHolder.values()
            accountHolder = list(accountHolder)
            accountHolder = accountHolder[0]
            temp = accountHolder
            accountHolder = list()

            for x in temp:
                accountHolder.append(temp[x])

            accountHolder = bearerBank(*accountHolder)
            chequeDetails.bearer = accountHolder

            # check file type
            if file_type_sign not in IMAGE_FILE_TYPES:
                context = {
                    'chequeDetails': chequeDetails,
                    'form': form,
                    'msg': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'ChequeClearingSystem/details.html', context)
            chequeDetails.chequeNumber = -1

            # extract details and match them with the database
            try:
                chequeDetails.save()

                acknowledgement = processing(chequeDetails.amount,
                                             BASE_DIR + '/ChequeClearingSystem/files/' + str(chequeDetails.cheque),
                                             accountHolder.full_name)
            except:
                acknowledgement = 'NAK'

            if acknowledgement == 'NAK':  # invalid Format
                message = 'Transaction Failed'
                return render(request, 'ChequeClearingSystem/details.html',
                              {'chequeDetails': chequeDetails, 'form': chequeUpload(), 'details': details,
                               'msg': message})
            elif acknowledgement[0] == 'NAK':  # Details verification failed
                try:
                    message = 'Transaction Failed. Balance in A/C ' + str(acknowledgement[3]) + ": " + str(
                        acknowledgement[2])
                    sendMessage(contactNumber=acknowledgement[1], msg=message)  # send the message to payee
                    message = 'Transaction Failed. Balance in A/C ' + str(accountHolder.accountNumber) + ": " + str(
                        accountHolder.balance)

                    sendMessage(contactNumber=accountHolder.contactNumber, msg=message)  # send the message to bearer
                except:
                    message = "Transaction Failed"

                return render(request, 'ChequeClearingSystem/details.html',
                              {'chequeDetails': chequeDetails, 'form': chequeUpload(), 'details': details,
                               'msg': message})
            else:
                try:
                    # payeeBank object for entry in payee Bank Database
                    payee = payeeBank.objects.filter(accountNumber=acknowledgement[1])
                    payee = payee.values()

ChequeClearingSystem/templates/ChequeClearingSystem/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'stylesheet/styles.css' %}" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".menu ul li a").click(function () {
                $(".menu ul li a").removeClass("active");
                $(this).addClass("active");
            });
        });
    </script>


    <title>{% block title %}Cheque Clearing System{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"><p align="center">PEB &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;Cheque Clearing System</p></a>
        </div>
    </div>
</nav>

<div class="container">
    <div>
        <p><span style="font-size:50px;color: white; "><b>PEB</b></span></p>
        <p><span style="font-size:30px;color: white; "><b>PEC &nbsp;ENGINEERING &nbsp;BANK</b></span></p>

    </div>

    <div>

        <ul class="menu">
            {% block menuButtons %}
            {% endblock %}
        </ul>
    </div>

</div>
{% block body %}

{% endblock %}

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br>

<footer>
    <div class="navbar navbar-inverse navbar-static-bottom navbar-fixed-bottom" role="navigation">
        <div class="navbar-text pull-left">
        </div>
        <div class="navbar-text pull-right">
        </div>
        <div class="navbar-text pull-left" id="bottomNav">
            &copy; Copyright &nbsp;&nbsp; Akshit Garg &nbsp; and &nbsp; Gaganpreet Singh Khurana
        </div>
    </div>
</footer>
</body>
</html>

ChequeClearingSystem/templates/ChequeClearingSystem/details.html
{% extends 'ChequeClearingSystem/base.html' %}

{% block title %}Details{% endblock %}
{% load static %}
{% block body %}
    {#    {% if error_message %}#}
    {#        <p><strong>{{ error_message }}</strong></p>#}
    {#    {% endif %}#}
    <div class="profile">
        <script>
            alert('{{ msg }}');

        </script>
        {#        {% for key,value in details.items %}#}
        {#            {% if key != 'profilePicture' %}#}
        {#                {{ key }}----------{{ value }}#}
        {#            {% endif %}<br><br>#}
        {##}
        {##}
        {#        {% endfor %}#}
    </div>
    <div class="menu">
        <form method="POST">
            {% csrf_token %}
            <button type="submit" formaction="{% url 'ChequeClearingSystem:logout' %}" class="link-button">Logout
            </button>
            <button type="submit" formaction="{% url 'ChequeClearingSystem:new_account' %}" class="link-button">New
                Account
            </button>
        </form>
    </div>
    <div class="box" id="login">
        <h2><b>Details</b></h2><br><br><br>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'ChequeClearingSystem/form-template.html' %}
            <div style="text-align: center;">
                <button type="submit">Submit</button>
            </div>
        </form>
        <br>
    </div>

{% endblock %}

ChequeClearingSystem/templates/ChequeClearingSystem/form-template.html
{% for field in form %}
    {#    <div class="box">#}
    {#        <div class="col-sm-offset-2 col-sm-10">#}
    {#            <span class="text-danger small">{{ field.errors }}</span>#}
    {#        </div>#}
    {#        <label class="control-label col-sm-2">{{ field.label_tag }}</label>#}
    <div class="inputBox">
        {{ field }}
        <label>{{ field.label }}</label>
    </div>
    {#    </div>#}
{% endfor %}

ChequeClearingSystem/templates/ChequeClearingSystem/login.html
{% extends 'ChequeClearingSystem/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}
    {#    {% if error_message %}#}
    {#        <p><strong>{{ error_message }}</strong></p>#}
    {#    {% endif %}#}
    <div class="box" id="login">
        <h2><b>LOGIN</b></h2><br><br><br>

        <form action="" method="post">
            {% csrf_token %}
            {% include 'ChequeClearingSystem/form-template.html' %}
            <div style="text-align: center;">
                <button type="submit">Login</button>
            </div>
        </form>
        <br>
        <form>
            <div style="text-align: center;">
                <button type="submit" formaction="{% url 'ChequeClearingSystem:register' %}">Register</button>
            </div>
        </form>
    </div>
{% endblock %}

ChequeClearingSystem/templates/ChequeClearingSystem/new_account.html
{% extends 'ChequeClearingSystem/base.html' %}
{% block title %}New Account{% endblock %}

{% block body %}
    {#    {% if error_message %}#}
    {#        <p><strong>{{ error_message }}</strong></p>#}
    {#    {% endif %}#}
    <div class="box" id="login">
        <h2><b>LOGIN</b></h2><br><br><br>

        <form action="" method="post">
            {% csrf_token %}
            {% include 'ChequeClearingSystem/form-template.html' %}
            <div style="text-align: center;">
                <button type="submit">Create</button>
            </div>
        </form>
        <br>
        <form method="post">
            {% csrf_token %}
            <div style="text-align: center;">
                <button type="submit" formaction="{% url 'ChequeClearingSystem:profile' %}">Back to Profile</button>
            </div>
        </form>
    </div>
{% endblock %}

ChequeClearingSystem/templates/ChequeClearingSystem/registration_form.html
{% extends 'ChequeClearingSystem/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
    {#    {% if error_message %}#}
    {#        <p><strong>{{ error_message }}</strong></p>#}
    {#    {% endif %}#}
    <div class="box" id="login">
        <h2><b>REGISTER</b></h2><br><br><br>

        <form action="" method="post">
            {% csrf_token %}
            {% include 'ChequeClearingSystem/form-template.html' %}
            <div style="text-align: center;">
                <button type="submit">Register</button>
            </div>
        </form>
        <br>
        <form>
            <div style="text-align: center;">
                <button type="submit" formaction="{% url 'ChequeClearingSystem:main' %}">Back to Login</button>
            </div>
        </form>
    </div>
{% endblock %}